options(stringsAsFactors=FALSE)
csvSet <- read.csv("household_power_consumption.txt",header=TRUE,sep=";")
csvSet$Global_active_power <- as.numeric(csvSet$Global_active_power)
csvSet$Date <- as.Date(csvSet$Date,format="%d/%m/%Y")
dateSet <- subset(csvSet,Date >= as.Date("2007-02-01","%Y-%m-%d"))
dateSet <- subset(dateSet,Date <= as.Date("2007-02-02","%Y-%m-%d"))
dateSet$Time <- paste(dateSet$Date,dateSet$Time,sep=" ")
dateSet$Time <- strptime(dateSet$Time,format="%Y-%m-%d %T")
dateSet$Sub_metering_1 <- as.numeric(dateSet$Sub_metering_1)
dateSet$Sub_metering_2 <- as.numeric(dateSet$Sub_metering_2)
dateSet$Voltage <- as.numeric(dateSet$Voltage)
dateSet$Global_reactive_power <- as.numeric(dateSet$Global_reactive_power)
png("plot4.png",width=480,height=480)
par(mfrow=c(2,2))
with(dateSet,plot(Time,Global_active_power,"l",ylab="Global Active Power (kilowatts)",xlab=""))
with(dateSet,plot(Time,Voltage,"l",ylab="Voltage",xlab="datetime"))
with(dateSet,plot(Time,Sub_metering_1,xlab="",ylab="Energy sub metering","l",col="black"))
with(dateSet,lines(Time,Sub_metering_2,col="red"))
with(dateSet,lines(Time,Sub_metering_3,col="blue"))
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lwd="1",box.lwd="0")
with(dateSet,plot(Time,Global_reactive_power,"l",ylab="Global_reactive_power",xlab="datetime"))
dev.off()