options(stringsAsFactors=FALSE)
csvSet <- read.csv("household_power_consumption.txt",header=TRUE,sep=";")
csvSet$Global_active_power <- as.numeric(csvSet$Global_active_power)
csvSet$Date <- as.Date(csvSet$Date,format="%d/%m/%Y")
dateSet <- subset(csvSet,Date >= as.Date("2007-02-01","%Y-%m-%d"))
dateSet <- subset(dateSet,Date <= as.Date("2007-02-02","%Y-%m-%d"))
dateSet$Time <- paste(dateSet$Date,dateSet$Time,sep=" ")
dateSet$Time <- strptime(dateSet$Time,format="%Y-%m-%d %T")
dateSet$Sub_metering_1 <- as.numeric(dateSet$Sub_metering_1)
dateSet$Sub_metering_2 <- as.numeric(dateSet$Sub_metering_2)
png("plot3.png",width=480,height=480)
with(dateSet,plot(Time,Sub_metering_1,xlab="",ylab="Energy sub metering","l",col="black"))
with(dateSet,lines(Time,Sub_metering_2,col="red"))
with(dateSet,lines(Time,Sub_metering_3,col="blue"))
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lwd="1")
dev.off()