options(stringsAsFactors=FALSE)
csvSet <- read.csv("household_power_consumption.txt",header=TRUE,sep=";")
csvSet$Global_active_power <- as.numeric(csvSet$Global_active_power)
csvSet$Date <- as.Date(csvSet$Date,format="%d/%m/%Y")
dateSet <- subset(csvSet,Date >= as.Date("2007-02-01","%Y-%m-%d"))
dateSet <- subset(dateSet,Date <= as.Date("2007-02-02","%Y-%m-%d"))
dateSet$Time <- paste(dateSet$Date,dateSet$Time,sep=" ")
dateSet$Time <- strptime(dateSet$Time,format="%Y-%m-%d %T")
png("plot2.png",width=480,height=480)
with(dateSet,plot(Time,Global_active_power,"l",ylab="Global Active Power (kilowatts)",xlab=""))
dev.off()